version: '3.8'

networks:
  kube_net:
    driver: bridge

services:
  kube:
    build: .
    # image: kube-news:0.1
    networks:
      kube_net:
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_DATABASE: kubedevnews
      DB_USERNAME: kubedevnews
      DB_PASSWORD: Pg#123
      DB_HOST: postgres

  postgres:
    image: postgres
    networks:
      kube_net:
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubedevnews"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: kubedevnews
      POSTGRES_PASSWORD: Pg#123
      POSTGRES_DB: kubedevnews